import { StyleSheet, Dimensions } from 'react-native'

import { colors, variables } from '../../constants'
import { getStatusBarHeight } from 'react-native-status-bar-height'

export default StyleSheet.create({
	flexOne: { flex: 1 },
	flexTwo: { flex: 2, justifyContent: 'flex-end' },
	container: { flex: 1, backgroundColor: colors.xxLightGrey },
	headerView: {
		flexDirection: 'row',
		justifyContent: 'space-around',
		alignItems: 'center',
		marginTop: getStatusBarHeight() + variables.textPadding,
		marginHorizontal: variables.appMargin,
	},
	contentView: { flex: 1, justifyContent: 'center' },
	keyboardAvoidingView: {
		flex: 1,
		justifyContent: 'flex-end',
	},
	phoneContentView: { flex: 1, justifyContent: 'space-between' },
	scrollView: {
		justifyContent: 'center',
		paddingVertical: variables.appMargin,
	},
	titleContainer: { marginTop: Dimensions.get('window').height * 0.1 },
	title: {
		fontSize: 25,
		fontWeight: '700',
		color: colors.brownishGrey,
		lineHeight: 37,
		paddingBottom: variables.appMargin,
		paddingHorizontal: variables.appMargin,
	},
	titleWithImage: { marginTop: variables.appMargin, marginBottom: 0 },
	noMargin: { marginBottom: 0 },
	marginTop: { marginTop: '15%' },
	marginBottom: { marginBottom: '15%' },
	subtitle: {
		fontSize: 18,
		fontWeight: '400',
		color: colors.brownishGrey,
		lineHeight: 30,
		marginBottom: '15%',
		paddingLeft: variables.appMargin,
		paddingRight: variables.appMargin * 2,
	},
	image: { height: 60, aspectRatio: 1, marginHorizontal: variables.appMargin },
	bottomView: { marginHorizontal: variables.appMargin },
	textButton: {
		alignItems: 'flex-start',
		marginLeft: variables.appMargin,
		marginBottom: variables.textPadding,
	},
	imageContainer: { flex: 1, justifyContent: 'center' },
	flatList: { paddingHorizontal: variables.appMargin },
	actionButtonContainer: {
		alignItems: 'flex-end',
		marginRight: 30,
		marginBottom: 50,
	},
	actionButton: {
		paddingHorizontal: variables.textPadding,
		backgroundColor: colors.lightGrey,
		borderWidth: 0,
	},
	actionButtonTitle: {
		fontSize: 18,
		fontWeight: '700',
		color: colors.brownishGrey,
	},
	actionButtonTitleSelected: { color: colors.white },
	leftAlignedActionButton: {
		alignSelf: 'baseline',
		paddingHorizontal: variables.textPadding,
		marginLeft: variables.appMargin,
		marginBottom: variables.textPadding,
		borderWidth: 0,
		height: 50,
	},
	lightActionButton: { backgroundColor: colors.lightGrey },
	xLightActionButton: { backgroundColor: colors.xLightGrey },
	textButtonContainer: {
		flex: 1,
		alignSelf: 'baseline',
		justifyContent: 'flex-end',
		padding: variables.appMargin,
		opacity: 0.8,
	},
	actionButtonSelected: { backgroundColor: colors.brownishGrey },
	bitInformation: {
		fontSize: 20,
		fontWeight: '700',
		color: colors.brownishGrey,
		lineHeight: 30,
		paddingVertical: variables.textPadding,
		paddingLeft: variables.appMargin,
		paddingRight: '10%',
	},
	addAnotherTinContainer: { alignSelf: 'center' },
	addAnotherTin: { fontWeight: '400', textAlign: 'center' },
	halaView: {
		position: 'absolute',
		width: '100%',
		height: '100%',
		backgroundColor: colors.xxLightGrey,
		justifyContent: 'center',
		alignItems: 'center',
	},
	popupImage: {
		height: 90,
		aspectRatio: 1,
		marginHorizontal: variables.appMargin,
	},
	resendButton: { fontSize: 15, fontWeight: '700', color: colors.brownishGrey },
	resendTimer: { fontSize: 15, fontWeight: '600', color: colors.brownishGrey },
	resendContainer: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		paddingHorizontal: variables.appMargin,
		paddingVertical: 10,
	},
	passcodeView: { paddingVertical: variables.appMargin },
	halaTitle: { textAlign: 'center', paddingHorizontal: '10%' },
})
