import LocalizedStrings from 'react-native-localization'

export default new LocalizedStrings({
	en: {
		appName: 'Digital Attacker',
		accountName: 'Account Name',
		iban: 'IBAN',
		addMoney: 'Add Money',
		accountNumber: 'Account Number',
		swiftCode: 'SWIFT Code',
		shareIBANPlaceholder:
			'Use this IBAN details to add money from another bank account so you will enjoy banking with us.',
		share: 'Share',
		successful: 'Successful!',
		sentTo: 'Sent to',
		done: 'Done',
		makeAnotherTransfer: 'Make another Transfer',
		resendCode: 'Resend Code',
		transfer: 'Transfer',
		transferTo: 'Transfer to',
		fromAccount: 'From Account',
		amount: 'Amount',
		localCurrency: 'SAR',
		purpose: 'Purpose',
		purposeDetails: 'Purpose Details',
		scheduleTransfer: 'Schedule the transfer',
		continue: 'Continue',
		toBankAccount: 'To a bank account',
		toContact: 'To a contact',
		recent: 'Recent',
		allBeneficiaries: 'All Beneficiaries',
		newBeneficiary: 'New Beneficiary',
		letsAddNewBeneficiary: `Let's add your first beneficiary!`,
		letsAddNewBeneficiaryDesc: `You don't have beneficiaries yet, why don't you try to add your first one? :)`,
		delete: 'Delete',
		deleteBeneficiaryPrefix: 'Are you sure you want to delete',
		deleteBeneficiarySuffix: 'from your beneficiary list?',
		deleteBeneficiaryConfirm: 'Yes, delete it',
		cancel: 'Cancel',
		editBeneficiary: 'Edit Beneficiary',
		saveChanges: 'Save Changes',
		addBeneficiary: 'Add Beneficiary',
		toAccount: 'To Account',
		transactionFee: 'Transaction fee',
		transactionDate: 'Transaction date',
		vat: 'VAT',
		vatPercentage: 'VAT (5%)',
		valueDate: 'Value date',
		confirmAndTransfer: 'Confirm and transfer',
		enterOTP: 'Enter OTP',
		weSentCode: 'We sent a code to',
		beneficiaryFullname: 'Beneficiary Full Name',
		beneficiaryNickname: 'Beneficiary Nickname',
		optional: ' (Optional)',
		bankName: 'Bank Name',
		beneficiaryAddress: 'Beneficiary Address',
		newTransfer: 'New Transfer',
		deleteBeneficiary: 'Delete Beneficiary',
		selectAnItem: 'Select an item...',
		incorrectOTP: 'Incorrect OTP, please try again',
		searchBeneficiary: 'Search beneficiary',
		pay: 'Pay',
		details: 'Details',
		accountDetails: 'Account Details',
		dataOpened: 'Date Opened',
		oops: 'Oops!',
		noTransactionsYet: 'You have not made any\ntransactions yet',
		iAmNewToBank: `I'm new to`,
		login: 'Login',
		english: 'English',
		arabic: 'Arabic',
		whatsYourNumber: `What's your mobile number?`,
		signInWithPasscode: 'Sign in with passcode',
		faceIdTitle: 'Would you like to use\nFace ID too?',
		activateFaceId: 'Activate Face ID',
		touchIdTitle: 'Would you like to use\nTouch ID too?',
		activateTouchId: 'Activate Touch ID',
		noThanks: 'No, thanks',
		sessionExpired: 'Session Expired',
		sessionExpiredDesc:
			'It looks like your session has expired! Please log in again',
		sorry: 'Sorry!',
		noInternet:
			'No internet connection. Make sure that Wi-Fi or mobile data is turned on, then try again',
		appMaintenance:
			'We are building a better bank for you! App maintenance will take place on',
		between: 'between',
		and: 'and',
		deviceNonCompliant: 'Device Non-Compliant',
		deviceNonCompliantDesc:
			'The app can not be used because your device does not adhere to our banking standards.',
		numberNotRecognised: 'Number not recognised',
		numberNotRecognisedDesc:
			'There is no account registered with this mobile number. Would you like to open an account?',
		userBlocked: 'User Blocked',
		userBlockedDesc:
			'Your access to this application has been locked as there were too many failed attemps\nPlease reset your passcode.',
		resetPasscode: 'Reset Passcode',
		ok: 'OK',
		touchIdFallback: 'Show Passcode',
		touchIdNotSupported: 'Touch ID Not Supported',
		faceIdNotSupported: 'Face ID Not Supported',
		touchIdDesc: 'Use Touch ID to sign in',
		faceIdDesc: 'Use Face ID to sign in',
		authenticatedSuccessfully: 'Authenticated successfully',
		next: 'Next',
		letsGo: `Let's go`,
		qualifyingTitle: 'Open a free account in 5 minutes, straight from your app',
		qualifyingThreeSteps: 'Here are 3 steps, you will need to do:',
		qualifyingStep1: 'Sign up with your Saudi phone number',
		qualifyingStep2: 'Verify your identity with Absher',
		qualifyingStep3: 'Answer some questions about yourself',
		qualifyingMorePoints: `You'll need to know a few more points...`,
		qualifyingPoint1: 'You have to be at least 18 or above years old',
		qualifyingPoint2: 'You are not a political exposed person',
		qualifyingPoint2Desc:
			'This information means that you are currently not holding one of the diplomatic, judiciary, or military status.',
		qualifyingPoint3: 'You are not a US person',
		qualifyingPoint3Desc:
			'This information means that an individual is a citizen if tht person was born in the United States or if the individual has been naturalized as a US citizen.',
		agreeToFollowing: 'I agree to the following',
		termsAndCondition: 'Terms and Conditions',
		termsAndConditionTitle: 'Digital Attacker Account Terms and Conditions',
		termsAndConditionInfo:
			'1. Digital Attacker shall be responsible for opening a current account for its customers, in which it shall record all its credit or debit amounts, either in cash or transfer of any kind.\n\n2. The Company may use the amounts recorded in such account, with a guarantee to pay the same upon request. The customer is not entitled to receive interests for such amounts as being prohibited under Sharia laws.\n\n3. The dealing in the mentioned account shall be only by the customer him/herself or by his/her representative and shall notify the Company in writing.\n\n4. The customer authorizes the Company without referring to the customer to credit his/her account by the cheques or money deposited by him/herself or others in his/her account.',
		whatCanWeCallYou: 'What can we call you?',
		whatsYourNumberToVerify: `What's your mobile phone number? We'll need to\nverify it.`,
		dontHaveKSANumber: `I don't have a Saudi mobile number`,
		notSaudiMobileDesc: `Unfortunately we're currently not able to offer accounts to people without a Saudi mobile phone number.\n\nWe're working to add this as soon as possible. Please check back soon!`,
		existingMobileDesc:
			'You have already an account with us.\n\n Please log in into your account.',
		error: 'Error!',
		backToLogin: 'Back to Log in',
		thanksWeSentYouCode: `Thanks! We've sent you a code by text.`,
		whatsYourEmail: `What's your email address?`,
		wellSendVerificationLink: `We'll send a verification link to this email address that you can click to verify your email address within 24 hours from now on.`,
		setYourLoginPasscode: `Great! Your email address is saved now! Let's set your login passcode.`,
		reEnterToBeCertain: 'Re-enter it, just to be\ncertain.',
		weAreAlmostDone: `We're almost done, just a few more questions to go. Your answers will help to get to know you further more!  `,
		whatsYourCountryOfBirth: `Great! What's your\ncountry of birth?`,
		areYouWorking: 'So, are you working at the moment?',
		iAmAnEmployee: `I'm an employee`,
		iAmABusinessOwner: `I'm a business owner`,
		iAmAStudent: `I'm a student`,
		iAmRetired: `I'm retired`,
		iAmNotWorking: `I'm not working as of this moment`,
		whatsYourOccupation: `Great! What's your\noccupation?`,
		whatsYourIncomeSouce: `Sounds fun! Where does your income come from? You can choose more than one option.`,
		salaryWithAllowances: 'Salary (inc. allowances)',
		businessEarnings: 'Business earnings',
		rentalIncome: 'Rental income',
		investmentProducts: 'Investment products',
		somethingElse: 'Something else',
		totalIncome: `What would you say is your total income per month, roughly? (Don't worry, we won't share this with anybody).`,
		whatAreYouPlanning: 'What are you planning to use this account for?',
		mySalary: 'My salary',
		mySavings: 'My savings',
		governmentWelfare: 'Government welfare',
		areYouUSCitizen:
			'Are you a US Citizen,\nresident or liable for US income taxes?',
		noImNot: `No, I'm not`,
		yes: 'Yes',
		backToHomePage: 'Back to Home Page',
		whatMakesUSPerson: 'What makes me a US person?',
		areYouResidentForTax:
			'Great, last question! Are you a resident for tax purposes of any countries other than Saudi Arabia?',
		noJustKSA: 'No, just Saudi Arabia',
		weNeedFewInformation: `OK, we'll need a few bits of information`,
		iHaveTin: 'I have a TIN number',
		iDontHaveTin: `I don't have a TIN`,
		haveMultipleResidencies: 'Have multiple residencies?',
		addAnotherTin: 'Add another TIN',
		pleaseSpecify: 'Please specify',
		taxIdentityNumber: 'Tax Identity Number',
		whatMakesUSPersonInfo: `Born in the United States\n\nBorn outside the United States of a US parent Naturalized citizens Green Card Holders Tax residents\n\nAll US citizens.  An individual is a citizen if that person was born in the United States or if the individual has been naturalized as a US citizen.\n\nYou can also be a US citizen, even if born outside the United States if one or both of your parents are US citizens.\n\nYou are a ‘tax resident’ of the United States.  You can become a tax resident under two rules: 1) The ‘substantial presence test’.   This is a ‘day count test and based on the number of days you are in the US over a three year period and 2) The ‘green card’ test.  A person who has obtained a ‘green card’ has been granted the right to lawful permanent residence in the United States.`,
		selectCountry: 'Select Country',
		hala: 'Hala!',
		marhaba: 'Marhaba!',
		niceToMeetYou: 'Nice to meet you,\n',
		couldntFindResult: `Sorry, we couldn't find any result, please try with different words`,
		noneUSAccountDesc: `Unfortunately we're currently now unable to offer account to US persons. We're working to add this as soon as possible.\n\nPlease visit our nearest branch.`,
		usCitizenDesc: `Unfortunately we're currently now unable to offer account to US persons. We're working to add this as soon as possible.\n\nWe will notify you when this is available.`,
		goToNearestBranch: 'Go to nearest branch',
		allDonePrefix: 'All done! Thanks ',
		allDoneSuffix:
			', you got throught that super quickly. Now, the fun part...',
		ibanCopied: 'IBAN copied to clipboard',
		currentAccountBalance: 'Current account balance: ',
		dateOfTransfer: 'Date of transfer',
		changeDate: 'Change date',
		oneOff: 'One off',
		recurring: 'Recurring',
		recurringPlaceholder: 'Weekly or monthly standing order',
		edit: 'Edit',
		totalAmount: 'Total amount',
		frequency: 'Frequency',
		startDate: 'Start date',
		endDate: 'End date',
		recurrencyPlaceholder:
			'If the date coincides with a non-business day,\nthe transfer will be submitted the previous day.',
		setupRecurringTransfer: 'Set up recurring transfer',
		recurrency: 'Recurrency',
		frequencyEmpty: 'Frequency cannot be empty',
		startDateEmpty: 'Start date cannot be empty',
		endDateEmpty: 'End date cannot be empty',
		typeOfTransfer: 'Type of transfer',
		personalInfo: 'Personal Information',
		absher: 'Absher',
		businessInfo: 'Business Information',
		continueToAbsher: 'Continue to Absher',
		iDontHaveAbsher: `I don't have Absher`,
		verifyYourIdentityTitle: 'We need you to verify your identity with Absher',
		verifyYourIdentityInfo:
			'We just want to make sure that it is really you. So you need to log in to your Absher account',
		greatJob: 'Great job',
		yourPasscodeIsSet: 'Your passcode is now set',
		nice: 'Nice, ',
		youAreRegisteredPrefix: 'You are now registered in ',
		youAreRegisteredSuffix:
			' and we linked the app to your name.\n\nAs your progress is saved, you can log back in at any time.',
		yourAccountIsVerified: 'Your Absher account has been verified.',
		noAbsherAccountDesc: `You can't open an account without having an Absher account.\n\nPlease visit our nearest branch.`,
		contactSupport: 'Contact Support',
		myFeed: 'My feed',
		payAndTransfer: 'Pay & transfer',
		moneyCoach: 'Money coach',
	},
	ar: {},
})
